config:
  credentials_path: ~/.echo_credentials/credentials.json
  token_path: ./data/token.pickle
  telegram_token: 8117472584:AAFFJfNrNRBfLrLFYINwy3zqdo6DX9CnT5w
  database_path: ./data/echo.db
  openai_api_key: "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" # <-- ADD THIS LINE