# Team Name Mappings
# Maps common aliases to canonical team names used by CricketData.org

international:
  India:
    - India
    - IND
    - Team India
    - Bharat
    - BCCI
  Australia:
    - Australia
    - AUS
    - Aussies
  England:
    - England
    - ENG
    - Poms
  Pakistan:
    - Pakistan
    - PAK
  South Africa:
    - South Africa
    - SA
    - RSA
    - Proteas
  New Zealand:
    - New Zealand
    - NZ
    - Kiwis
    - Black Caps
  Sri Lanka:
    - Sri Lanka
    - SL
    - SRI
    - Lanka
  West Indies:
    - West Indies
    - WI
    - Windies
  Bangladesh:
    - Bangladesh
    - BAN
    - BD
    - Tigers
  Afghanistan:
    - Afghanistan
    - AFG
  Zimbabwe:
    - Zimbabwe
    - ZIM
  Ireland:
    - Ireland
    - IRE

ipl:
  Mumbai Indians:
    - Mumbai Indians
    - MI
    - Mumbai
  Chennai Super Kings:
    - Chennai Super Kings
    - CSK
    - Chennai
  Royal Challengers Bengaluru:
    - Royal Challengers Bengaluru
    - Royal Challengers Bangalore
    - RCB
    - Bengaluru
    - Bangalore
  Kolkata Knight Riders:
    - Kolkata Knight Riders
    - KKR
    - Kolkata
  Delhi Capitals:
    - Delhi Capitals
    - DC
    - Delhi
  Rajasthan Royals:
    - Rajasthan Royals
    - RR
    - Rajasthan
  Punjab Kings:
    - Punjab Kings
    - PBKS
    - Punjab
    - Kings XI Punjab
    - KXIP
  Sunrisers Hyderabad:
    - Sunrisers Hyderabad
    - SRH
    - Hyderabad
    - Sunrisers
  Gujarat Titans:
    - Gujarat Titans
    - GT
    - Gujarat
  Lucknow Super Giants:
    - Lucknow Super Giants
    - LSG
    - Lucknow
